station_id: alp-02
location:
  latitude: 46.5651
  longitude: 12.3214
  altitude_m: 1200
generation:
  interval_seconds: 6
  temperature_base: 14.0
  humidity_base: 78.0
  wind_speed_base: 12.0
  pressure_base: 878.0
  solar_radiation_base: 220.0
  rain_probability: 0.30
