station_id: alp-04
location:
  latitude: 46.5651
  longitude: 12.3214
  altitude_m: 1500
generation:
  interval_seconds: 8
  temperature_base: 12.5
  humidity_base: 78.0
  wind_speed_base: 15.0
  pressure_base: 848.0
  solar_radiation_base: 210.0
  rain_probability: 0.15
