station_id: alp-09
location:
  latitude: 46.5651
  longitude: 12.3214
  altitude_m: 1850
generation:
  interval_seconds: 180
  temperature_base: 12.5
  humidity_base: 78.0
  wind_speed_base: 15.0
  pressure_base: 1002.0
  solar_radiation_base: 210.0
  rain_probability: 0.15
